#!/bin/bash

## #ddev-generated
## Description: Analyze code to find bugs with PHPStan.
## Example: ddev xb-phpstan
## Aliases: phpstan,stan

cd "$DDEV_COMPOSER_ROOT/$DDEV_DOCROOT" || exit 1

../vendor/bin/phpstan \
  analyze \
  --configuration=modules/contrib/canvas/phpstan.neon \
  --memory-limit=1G \
  --autoload-file=modules/contrib/canvas/phpstan_rules/autoload.php \
  modules/contrib/canvas

# If we wanted to run exactly the same than composer or Gitlab CI:
# cd "$DDEV_COMPOSER_ROOT/$DDEV_DOCROOT/modules/contrib/canvas" || exit 1
# ../../../../vendor/bin/composer run phpstan
